### ISSUE TITLE
Support for bucket object prefixes

### ISSUE THREAD

**Issue by pete-woods** [salrashid123/downscoped_token#2]
At present (unlike on AWS) if you want to create a service that grants per-project storage and hands out credentials for it, you have to create a bucket-per-user, which is far from ideal.

See AWS's support article on their equivalent feature:
https://aws.amazon.com/code/credential-management-for-mobile-applications/

**Comment by salrashid123** [comment]
i'm not sure i understand.  if you need a CAB token that is at the bucket level, you can specify the bucketname in the condition

```
Expression: "resource.name.startsWith(\"projects/_/buckets/your_bucket_name\")",
```

https://cloud.google.com/storage/docs/access-control/iam
